### ISSUE TITLE
[Bug]: <YOUR ISSUE TITLE>

### ISSUE THREAD

**Issue by Precha24** [Shopify/shopify-cli#2756]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

ใช้งานได้

### Actual behavior

ไม่เกิดการใช้งาน

### Reproduction steps

1.
2.
3.

### Operating System

วินโดวส์11

### CLI version (run `shopify version` if you're not sure)

2.10.0

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/shopify-cli/issues/2728
- [ ] https://github.com/Shopify/cli/issues/2017
- [ ] https://github.com/Shopify/shopify-cli/issues/2727
- [ ] https://github.com/Shopify/shopify-cli/issues/2727
```

**Comment by alvaro-shopify** [comment]
@Precha24 closing this issue as it's seems any kind of test you are doing. In case you have a concrete issue, please create a new one with the details of the error. Thanks

**Comment by Precha24** [comment]
What do we have to do?
